### ISSUE TITLE
Use personal/professional website in pkgdown website

### ISSUE THREAD

**Issue by mcanouil** [briatte/ggnetwork#43]
Hi @briatte 

would it be possible to change the current `_pkgdown.yml` file to add my website?
It will add a href link to my name in the authors list on the pkgdown website as for [NACHO](https://mcanouil.github.io/NACHO/).

```yaml
template:
  params:
    bootswatch: simplex

development:
  mode: auto

authors:
  Mickaël Canouil:
    href: http://mickael.canouil.fr

```

You can add your own website as well

```yaml
template:
  params:
    bootswatch: simplex

development:
  mode: auto

authors:
  Mickaël Canouil:
    href: http://mickael.canouil.fr
  François Briatte:
    href: http://f.briatte.org/r

```

Thanks!
