### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by briatte** [briatte/ggnetwork#66]
https://ropensci.org/blog/2020/11/19/moving-away-travis/

Old `.travis.yml` settings copied below for reference. `covr::coveralls()` is still mentioned, but was not in use.

Things to copy:

- [x] R CMD CHECK on R release and devel
- [x] Test coverage with Codecov
- [x] Deploy to GitHub Pages

All of those things are thankfully covered in the examples of `r-lib/actions`:

https://github.com/r-lib/actions/tree/master/examples

```yaml
language: R
cache: packages
sudo: true


env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
    - _R_CHECK_SYSTEM_CLOCK_=false

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'

r_github_packages:
  - r-lib/covr

matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: 3.5
  - r: 3.6

after_success:
  - Rscript -e 'covr::coveralls(); covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
```
